// Generated by gencpp from file vacum_bot/AddTwoInts.msg
// DO NOT EDIT!


#ifndef VACUM_BOT_MESSAGE_ADDTWOINTS_H
#define VACUM_BOT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <vacum_bot/AddTwoIntsRequest.h>
#include <vacum_bot/AddTwoIntsResponse.h>


namespace vacum_bot
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace vacum_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vacum_bot::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::vacum_bot::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::vacum_bot::AddTwoInts > {
  static const char* value()
  {
    return "vacum_bot/AddTwoInts";
  }

  static const char* value(const ::vacum_bot::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::vacum_bot::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::vacum_bot::AddTwoInts > 
template<>
struct MD5Sum< ::vacum_bot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vacum_bot::AddTwoInts >::value();
  }
  static const char* value(const ::vacum_bot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vacum_bot::AddTwoIntsRequest> should match 
// service_traits::DataType< ::vacum_bot::AddTwoInts > 
template<>
struct DataType< ::vacum_bot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::vacum_bot::AddTwoInts >::value();
  }
  static const char* value(const ::vacum_bot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vacum_bot::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::vacum_bot::AddTwoInts > 
template<>
struct MD5Sum< ::vacum_bot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vacum_bot::AddTwoInts >::value();
  }
  static const char* value(const ::vacum_bot::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vacum_bot::AddTwoIntsResponse> should match 
// service_traits::DataType< ::vacum_bot::AddTwoInts > 
template<>
struct DataType< ::vacum_bot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::vacum_bot::AddTwoInts >::value();
  }
  static const char* value(const ::vacum_bot::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VACUM_BOT_MESSAGE_ADDTWOINTS_H
